name: "fastapi-app-filebeat"
logging.metrics.enabled: false
xpack.security.enabled: false
xpack.monitoring.enabled: false
setup.ilm.enabled: false
setup.template.enabled: false

filebeat.inputs:
  - type: log
    scan_frequency: 1s
    enabled: true
    paths:
      - /src/logs/api.log
    fields:
      - service: fastapi-app
    fields_under_root: true
    multiline.type: pattern
    multiline.pattern: "^{[0-9]{4}-[0-9]{2}-[0-9]{2}"
    multiline.negate: true
    multiline.match: after
    processors:
      - decode_json_fields:
          fields: ["message"]
          target: "json"

output.elasticsearch:
  hosts: ["elasticsearch:9200"]
  index: "fastapi-app"
