services:
  elasticsearch:
    container_name: elasticsearch
    image: docker.elastic.co/elasticsearch/elasticsearch:8.15.0
    restart: always
    environment:
      - xpack.security.enabled=false
      - "discovery.type=single-node"
    volumes:
      - ./elasticsearch-data:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
  kibana:
    container_name: kibana
    image: docker.elastic.co/kibana/kibana:8.15.0
    restart: always
    environment:
      - "ELASTICSEARCH_HOSTS=http://elasticsearch:9200"
    ports:
      - 5601:5601
    depends_on:
      - elasticsearch
  filebeat:
    build:
      context: ./filebeat
    container_name: filebeat
    volumes:
      - ./fastapi-logs:/src/logs
  fastapi:
    build:
      context: .
      dockerfile: ./app/Dockerfile
    container_name: fastapi-app
    volumes:
      - ./fastapi-logs:/src/app/logs
    ports:
      - 8000:8000

